<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Kendaraan2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kendaraan')->insert([
            [
                'merk' => 'Toyota',
                'tipe' => 'Kijang',
                'jenis' => 'Non Sedan',
                'warna' => 'Silver',
                'plat_nomor' => 'H 1937 KF',
                'nilai_perolehan' => 194800000,
                'nilai_buku' => 194800000,
                'tgl_pembelian' => '2007-04-10',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 6,
                'no_mesin' => '1TR6355423',
                'no_rangka' => 'MHFXW42G372084820',
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'New Altis G A/T',
                'jenis' => 'Sedan',
                'warna' => 'Putih',
                'plat_nomor' => 'H 1098 UF',
                'nilai_perolehan' => 346000000,
                'nilai_buku' => 346000000,
                'tgl_pembelian' => '2011-03-23',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 4,
                'no_mesin' => '2ZRX069328',
                'no_rangka' => 'MR053REE2B4300631',
                'kapasitas' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Kijang Innova E',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'H 1097 UF',
                'nilai_perolehan' => 204000000,
                'nilai_buku' => 204000000,
                'tgl_pembelian' => '2011-03-23',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 4,
                'no_mesin' => '1TR7073770',
                'no_rangka' => 'MHFXW41G9B0043842',
                'kapasitas' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Innova V M/T',
                'jenis' => 'Non Sedan',
                'warna' => 'Silver',
                'plat_nomor' => 'H 1149 EP',
                'nilai_perolehan' => 282500000,
                'nilai_buku' => 282500000,
                'tgl_pembelian' => '2012-03-14',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Dex',
                'frekuensi_servis' => 3,
                'no_mesin' => '1TR7271521',
                'no_rangka' => 'MHFXW43G9C4064150',
                'kapasitas' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Isuzu',
                'tipe' => 'Elf',
                'jenis' => 'Non Sedan',
                'warna' => 'Putih',
                'plat_nomor' => 'H 1136 VS',
                'nilai_perolehan' => 508200000,
                'nilai_buku' => 508200000,
                'tgl_pembelian' => '2014-12-01',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Dex',
                'frekuensi_servis' => 2,
                'no_mesin' => 'M058107',
                'no_rangka' => 'MHCNHR55EEJ058107',
                'kapasitas' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Mitsubishi',
                'tipe' => 'All New Pajero Dakar Limited 4X2 A/T',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'H 1174 DP',
                'nilai_perolehan' => 514000000,
                'nilai_buku' => 514000000,
                'tgl_pembelian' => '2016-12-27',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Dex',
                'frekuensi_servis' => 2,
                'no_mesin' => '4N15UBC2862',
                'no_rangka' => 'MMBGUKR10GH038635',
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Innova V A/T',
                'jenis' => 'Non Sedan',
                'warna' => 'Cokelat',
                'plat_nomor' => 'H 1622 LA',
                'nilai_perolehan' => 362200000,
                'nilai_buku' => 362200000,
                'tgl_pembelian' => '2018-09-20',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Dex',
                'frekuensi_servis' => 2,
                'no_mesin' => '1TR-A525815',
                'no_rangka' => 'MHFGW8EM4JI022252',
                'kapasitas' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Honda',
                'tipe' => 'Accord',
                'jenis' => 'Sedan',
                'warna' => 'Putih',
                'plat_nomor' => 'H 1864 LA',
                'nilai_perolehan' => 631000000,
                'nilai_buku' => 631000000,
                'tgl_pembelian' => '2018-09-28',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 2,
                'no_mesin' => 'K24W33000314',
                'no_rangka' => 'MRHCR2640JP810072',
                'kapasitas' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Fortuner VRZ GR 4X2AT',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'H 1527 UH',
                'nilai_perolehan' => 556600000,
                'nilai_buku' => 556600000,
                'tgl_pembelian' => '2021-12-13',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Dex',
                'frekuensi_servis' => 1,
                'no_mesin' => '2GD-C925143',
                'no_rangka' => 'MHFAB8GS2M3023860',
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Innova Zenix 2.0 Q HV CVT TSS Modellista',
                'jenis' => 'Non Sedan',
                'warna' => 'Putih',
                'plat_nomor' => 'H 1618 LP',
                'nilai_perolehan' => 630000000,
                'nilai_buku' => 630000000,
                'tgl_pembelian' => '2024-08-13',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 1,
                'no_mesin' => 'M20A-NC52640',
                'no_rangka' => 'MHFABBAA9R0428071',
                'kapasitas' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
