<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;



class KendaraanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kendaraan')->insert([
            [
                'merk' => 'Toyota',
                'tipe' => 'Avanza',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'B1234XYZ',
                'nilai_perolehan' => 200000000,
                'nilai_buku' => 150000000,
                'tgl_pembelian' => '2020-01-15',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 5,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Honda',
                'tipe' => 'Civic',
                'jenis' => 'Sedan',
                'warna' => 'Merah',
                'plat_nomor' => 'D5678ABC',
                'nilai_perolehan' => 300000000,
                'nilai_buku' => 250000000,
                'tgl_pembelian' => '2019-08-20',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 3,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Suzuki',
                'tipe' => 'Ertiga',
                'jenis' => 'Non Sedan',
                'warna' => 'Putih',
                'plat_nomor' => 'E91011DEF',
                'nilai_perolehan' => 150000000,
                'nilai_buku' => 120000000,
                'tgl_pembelian' => '2021-05-10',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 2,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Daihatsu',
                'tipe' => 'Xenia',
                'jenis' => 'Non Sedan',
                'warna' => 'Silver',
                'plat_nomor' => 'F3456GHI',
                'nilai_perolehan' => 180000000,
                'nilai_buku' => 140000000,
                'tgl_pembelian' => '2018-11-25',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 4,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Mitsubishi',
                'tipe' => 'Pajero Sport',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'H7890JKL',
                'nilai_perolehan' => 500000000,
                'nilai_buku' => 450000000,
                'tgl_pembelian' => '2022-03-30',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 1,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Nissan',
                'tipe' => 'Terra',
                'jenis' => 'Non Sedan',
                'warna' => 'Cokelat',
                'plat_nomor' => 'B2345LMN',
                'nilai_perolehan' => 400000000,
                'nilai_buku' => 370000000,
                'tgl_pembelian' => '2021-09-15',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 3,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Fortuner',
                'jenis' => 'Non Sedan',
                'warna' => 'Putih',
                'plat_nomor' => 'D6789OPQ',
                'nilai_perolehan' => 550000000,
                'nilai_buku' => 500000000,
                'tgl_pembelian' => '2020-07-10',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Dex',
                'frekuensi_servis' => 2,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Avanza',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'B1234XXX',
                'nilai_perolehan' => 200000000,
                'nilai_buku' => 150000000,
                'tgl_pembelian' => '2019-01-15',
                'aset' => 'Tidak Guna',
                'status_ketersediaan' => 'Tidak Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 5,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Daihatsu',
                'tipe' => 'Xenia',
                'jenis' => 'Non Sedan',
                'warna' => 'Silver',
                'plat_nomor' => 'F3456GGG',
                'nilai_perolehan' => 180000000,
                'nilai_buku' => 140000000,
                'tgl_pembelian' => '2018-11-25',
                'aset' => 'Jual',
                'status_ketersediaan' => 'Tidak Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 4,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Mitsubishi',
                'tipe' => 'Pajero Sport',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'H7890JJJ',
                'nilai_perolehan' => 500000000,
                'nilai_buku' => 450000000,
                'tgl_pembelian' => '2022-03-30',
                'aset' => 'Jual',
                'status_ketersediaan' => 'Tidak Tersedia',
                'bahan_bakar' => 'Pertamax Dex',
                'frekuensi_servis' => 1,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Suzuki',
                'tipe' => 'Ertiga',
                'jenis' => 'Non Sedan',
                'warna' => 'Putih',
                'plat_nomor' => 'E91011DDD',
                'nilai_perolehan' => 150000000,
                'nilai_buku' => 120000000,
                'tgl_pembelian' => '2021-05-10',
                'aset' => 'Jual',
                'status_ketersediaan' => 'Tidak Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 2,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Avanza',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'B1234YYY',
                'nilai_perolehan' => 200000000,
                'nilai_buku' => 150000000,
                'tgl_pembelian' => '2020-01-15',
                'aset' => 'Lelang',
                'status_ketersediaan' => 'Tidak Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 5,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Toyota',
                'tipe' => 'Avanza',
                'jenis' => 'Non Sedan',
                'warna' => 'Hitam',
                'plat_nomor' => 'B1234ZYX',
                'nilai_perolehan' => 200000000,
                'nilai_buku' => 150000000,
                'tgl_pembelian' => '2020-01-15',
                'aset' => 'Jual',
                'status_ketersediaan' => 'Tidak Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 5,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            
            // 2 Data Motor
            [
                'merk' => 'Yamaha',
                'tipe' => 'NMAX',
                'jenis' => 'Motor',
                'warna' => 'Hitam',
                'plat_nomor' => 'AB1234XYZ',
                'nilai_perolehan' => 30000000,
                'nilai_buku' => 25000000,
                'tgl_pembelian' => '2022-01-01',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 2,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merk' => 'Honda',
                'tipe' => 'CBR 150',
                'jenis' => 'Motor',
                'warna' => 'Merah',
                'plat_nomor' => 'AB5678XYZ',
                'nilai_perolehan' => 40000000,
                'nilai_buku' => 35000000,
                'tgl_pembelian' => '2023-06-15',
                'aset' => 'Guna',
                'status_ketersediaan' => 'Tersedia',
                'bahan_bakar' => 'Pertamax Turbo',
                'frekuensi_servis' => 1,
                'no_mesin' => Str::random(17),
                'no_rangka' => Str::random(20),
                'kapasitas' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
